repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check (uv)
        language: system
        entry: uv
        args: ["run", "ruff", "check", "--fix"]
        pass_filenames: false
        types: [python]
        exclude: ^(.*/)?(alembic|migrations|dist|build|\.venv)/

      - id: ruff-format
        name: ruff format (uv)
        language: system
        entry: uv
        args: ["run", "ruff", "format"]
        pass_filenames: false
        types: [python]
        exclude: ^(.*/)?(alembic|migrations|dist|build|\.venv)/
  # mypy: 로컬 훅 (프로젝트 venv 사용)
  - repo: local
    hooks:
      - id: mypy
        name: mypy (uv)
        language: system
        entry: uv
        args: ["run", "mypy", "--config-file=pyproject.toml"]
        pass_filenames: false
        types: [python]
        # 파이썬 파일이 아닌 커밋에도 무조건 검사하고 싶다면 ↓ 두 줄 추가
        # always_run: true
        # files: ""   # (빈 정규식)
        exclude: ^(.*/)?(alembic|migrations|dist|build|\.venv)/